name: Deploy Terraform 

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy-terraform:
    runs-on: ubuntu-latest
    environment: production
    defaults:
      run:
        working-directory: ./tf
    permissions:
      id-token: write
    env:
      TF_VAR_project_id: ${{ vars.PROJECT_ID }}
      TF_VAR_topic_name: ${{ vars.TOPIC_NAME }}

    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
    
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
            workload_identity_provider: 'projects/548610614069/locations/global/workloadIdentityPools/narou-update-notify/providers/github-com'
            service_account: 'narou-update-notify@main-349812.iam.gserviceaccount.com'
      
      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - id: plan
        run: terraform plan -no-color

      - name : Terraform Apply
        id: apply
        run: terraform apply -auto-approve -no-color
        