# This is a basic workflow to help you get started with Actions

name: deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy:
    permissions:
      contents: 'read'
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      
      - id: auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.gcp_credentials }}'

      # Runs a single command using the runners shell
      - id: 'deploy'
        uses: 'google-github-actions/deploy-cloud-functions@v1'
        with:
          name: 'notify-pubsub'
          runtime: 'go121'
          entry_point: 'NotifyPubSub'
          region: 'asia-northeast1'
          project_id: '${{ secrets.gcp_project_id }}'
          event_trigger_type: 'google.pubsub.topic.publish'
          event_trigger_resource: 'projects/${{ secrets.gcp_project_id }}/topics/narou-notify'
          event_trigger_service: pubsub.googleapis.com
          secret_environment_variables: 'AWS_ACCESS_KEY=projects/${{ secrets.gcp_project_id }}/secrets/cloud-functions-narou-access-token/versions/1, AWS_SECRET_ACCESS_KEY=projects/${{ secrets.gcp_project_id }}/secrets/cloud-functions-narou-secret-access-token/versions/1, TO_ADDRESS=projects/${{ secrets.gcp_project_id }}/secrets/to-address/versions/1, FROM_ADDRESS=projects/${{ secrets.gcp_project_id }}/secrets/from-address/versions/1'
          
